name: Build VaultPro APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev zlib1g-dev libffi-dev libssl-dev
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install buildozer
        run: |
          pip install buildozer==1.5.0 cython==0.29.36
      - name: Build
        run: |
          yes | buildozer -v android debug
      - name: List bin
        if: always()
        run: ls -R bin || echo "no bin"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: VaultPro-A36-APK
          path: bin/
